### ISSUE TITLE
Настройка Gradle. Создание gitflow в репозитории

### ISSUE THREAD

**Issue by vikseal** [CashAdv/CashADV#1]
applicationId: app.cashadvisor
minSdk: 23
targetSdk/compileSdk: 34
build: Gradle 8.2+KTS+versions catalogs
dependencies: Hilt, Coroutines, Room, Navigation, Glide, Timber, ViewModel+Lifecycle(AppCompat, Material, etc), Firebase; Retrofit+Okhttp+Kotlinx.Serialization
dev и main протектед ветки(в dev  пушим только через pr)

**Comment by avanisimov** [comment]
папку .idea можно сразу удалить
у каждого разраба она будет своя

библиотеки с версиями по логике должны быть в settings.gradle.kts

**Comment by vladalexeco** [comment]
@avanisimov ok, я исправлю и оформлю в виде ПР.
