### ISSUE TITLE
Настройка CI/CD. Настройка автоматической сборки проекта.

### ISSUE THREAD

**Issue by vikseal** [CashAdv/CashADV#13]

**Comment by JudjinGM** [comment]
Aleksei Anisimov: 
тех информация по ключу:

1. Файл ключницы можно назвать как проек cashadvisor.jks
ключница предполагает возможность множества ключей, но у нас всегда будет только один
alias можно назвать просто app

2. Пароли ключницы и ключа желательно сделать разные

3. Ключницу можно положить в корень проекта, хранить его в коде нормально

4. Путь к ключнице и alias можно прописать в build.gradle - это в целом приемлимо
но вот пароли хранить в репозитории кода нельзя
локально на компе их можно положить в local.properties и доставать оттуда

5. На гитхабе это потом будет лежать в секретах проекта (но это уже отдельная история)
