### ISSUE TITLE
Настройка CI/CD. Настройка сборок приложения.

### ISSUE THREAD

**Issue by vikseal** [CashAdv/CashADV#2]
Сконфигурировать в gradle все возможные типы сборок.

Github actions
env: stage/prod
buildTypes: debug/test/release

**Comment by avanisimov** [comment]
Для начала нужна сконфигурировать в gradle все возможные типы сборок https://developer.android.com/build/build-variants
в нашем случае будет измерение env: stage/prod - в них будет отличаться путь к серверу
и помимо вариантов debug/release нужно добавить вариант test который для начала будет такой же как release
debug - только для разработчиков для запуска локально
test - для тестировщиков на этапе тестирования
prod - для заказчиков и публикации в магазин

для stage сборок нужно добавить applicationIdSuffix = ".stage". для прода ничего не добавляем
для debug сборок applicationIdSuffix = ".debug"
для test сборок applicationIdSuffix = ".test"


Далее нужно настроить 2 сценария автоматической сборки проекта через Github Actions
1 сценарий: проверка того, что приложение собирается при создании PR в ветку dev
2 сценарий: сборка тестового приложения и публикация в App Distribution для группы тестировщиков
