### ISSUE TITLE
Подключение к проекту и настройка Firebase в части crashlytics/analytics

### ISSUE THREAD

**Issue by vikseal** [CashAdv/CashADV#3]
После настройки https://github.com/CashAdv/CashADV/issues/1
В части crashlytics/analytics

**Comment by avanisimov** [comment]
1 - Хорошей практикой будет создать сразу 2 проекта в Firebase: Cash Advisor Test и Cash Advisor (тестовая и продовая версия), чтобы потом не путать статистику от реальных пользователей и от тестировщиков. В рамках разработки проекта мы будем в основном пользоваться Cash Advisor Test
2 - лучше создать проект из под отдельной, НЕ личной учетки. за этим надо обратититься к PM @vikseal (Нужна чисто техническая гугловая учетка, например cash.advisor.app@gmail.com)
3 - продовый applicationId будет app.cashadvisor, дебажный и тестовый - app.cashadvisor.debug app.cashadvisor.test

**Comment by vikseal** [comment]
Логин: app.cashadvisor
Пароль: !Q2w3e4r

**Comment by avanisimov** [comment]
@vikseal задача готова
