### ISSUE TITLE
Настроить логирование через Timber

### ISSUE THREAD

**Issue by avanisimov** [CashAdv/CashADV#37]
Посмотреть доку по https://github.com/JakeWharton/timber
настроить логгер так, чтобы для Debug и QA сборок все логи падали в Logcat
а для QA и Release сборок - варнинги и ошибки писались в крашлитику
для Release сборок все остальные типы логов никуда не писались

**Comment by artwist-polyakov** [comment]
@avanisimov нужна помощь по этой задаче.

Я набросал пару тестов осановываясь на том, что [тут](https://github.com/JakeWharton/timber/blob/trunk/timber-sample/src/main/java/com/example/timber/ExampleApp.java)
И у меня сейчас будет пара вопросов. Сам код можно смотреть [тут: три действующих лица это расширение, какой-то лог класс, который определяет как писать логи и собственно активити в котором мы это привяжем)](https://github.com/CashAdv/CashADV/commit/19f478808bb57f25be3affcb5526a5c48cdb8d09?diff=unified&w=0)

Вопросы:

- Как мне определить текущий конфиг. В `BuildConfig` который использован в примерах автора либы есть только DEBUG и больше ничего, только какие то коды версий.
- корректно ли сетап повесить в расширение? у нас кстати разве не будет класса App.kt в котором должны быть прописаны все такие конфиги?

**Comment by artwist-polyakov** [comment]
> сетап лучше делать в Application#onCreate

Спасибо за ответы, стало понятнее, только вот я не вижу у нас класса Application. Он точно есть?

**Comment by avanisimov** [comment]
> > сетап лучше делать в Application#onCreate
> 
> Спасибо за ответы, стало понятнее, только вот я не вижу у нас класса Application. Он точно есть?

его еще нет)

**Comment by artwist-polyakov** [comment]
@avanisimov что-то ничего не получается у меня с этими билд тайпами
Я прописываю вот так https://github.com/CashAdv/CashADV/commit/95efc351b6162d95552ed289293d565581bf8b2a это по аналогии с документацией гугла и ожидаю, что при попытке обращения к BuildConfig у меня будет доступ к свойству LOGGING_LEVEL, то его нет.

предполагаю, что вот этот импорт — не тот что нужен `import com.google.android.datatransport.BuildConfig`, но какой тоггда нужен ?
