### ISSUE TITLE
Подключение к проекту и настройка Firebase в части appdistribution

### ISSUE THREAD

**Issue by vikseal** [CashAdv/CashADV#4]
После настройки  issue https://github.com/CashAdv/CashADV/issues/3

**Comment by avanisimov** [comment]
когда будет готово https://github.com/CashAdv/CashADV/issues/3#issuecomment-1824573182
надо будет добавить плагин и возможность публиковать сборки в App Distribution
там сразу можно создать 2 группы: Testers, StakeHolders
Testers - те, кто будут смотреть каждую новую сборку из ветки dev
StakeHolders - будут смотреть готовый результат блока работ, после проверки тестерами
