### ISSUE TITLE
Разработать схемы переходов

### ISSUE THREAD

**Issue by vikseal** [CashAdv/CashADV#5]

**Comment by katana-13** [comment]
https://www.figma.com/file/jNtNVKgOBTqJNFLmvxuyxi/transition?type=design&node-id=129%3A1549&mode=design&t=ZNxR41euNyNe1WR2-1

**Comment by katana-13** [comment]
[Ссылка на диаграммы:](https://drive.google.com/file/d/1Knf-pX4lTpQZPYq0cmkm3XGiELNMaeyN/view?usp=sharing)
1. Вариантов использования. Отражает функции приложения
2. Потоков данных
  2.1 Концептуального уровня: общие потоки между участниками системы
  2.2 Логического уровня: потоки данных с учетом функций системы и хранилищ данных
3. **Диаграмма структуры интерфейса. Отражает экраны и переходы в приложении.**

**Comment by vikseal** [comment]
@avanisimov такая схема устроит?

**Comment by avanisimov** [comment]
@vikseal Схемы огонь, но есть вопросики
думаю эффективнее будет голосом обсудить

**Comment by vikseal** [comment]
> @vikseal Схемы огонь, но есть вопросики думаю эффективнее будет голосом обсудить
Посмотрим сегодня вечером
