### ISSUE TITLE
Подтверждение email (регистрация)

### ISSUE THREAD

**Issue by katana-13** [CashAdv/CashADV#58]
## UC-2 Ввод кода подтверждения (продолжение регистрации)

Предусловие : Пользователь отправил эл.почту / пароль при регистрации
Триггер: Успешное выполнение сценария UC-1 Регистрация пользователя в приложении (#48)
Критерии приемки:
1. Отображение пользователю экрана [Enter verification email code](https://www.figma.com/file/jZ6rHddBpxOdgl1uPAvyWI/Cash-Advisor-App?type=design&node-id=2246-1581&mode=design&t=FFZEGoqCY3V0sFCR-4)

⚡ data и domain слой для логина, регистрации и кодов подтверждения для логина и регистрации, а также валидация для email, пароля и кодов подтверждения реализована в рамках #54 и #55

Если пользователем не получено письмо, то он может повторить отправку кода через 30 сек  (кнопка становится активна). Для этого можно сохранять данные о логине/пароле на клиенте и отправлять новый запрос для кода по тому же эндпойнту [(/auth/register)](https://212.233.78.3:8080/swagger/docs/index.html#/Auth/post_auth_register)
Количество доступных попыток - 3 
Счетчик попыток создается при выполнении запроса пользователя на регистрацию.
Если код введен не верно, счетчик попыток также уменьшается
У пользователя должна быть возможность обратиться в поддержку ( #77)
![image](https://github.com/CashAdv/CashADV/assets/80758874/615dddb7-4527-4261-9243-90a4926e135d)

2. Ввод пользователем цифр подтверждения, полученных в письме на email
[Апи получения кода для разработки](https://212.233.78.3:8080/swagger/docs/index.html#/Dev/get_dev_confirmation_code_get) 

3. После ввода пользователем цифр выполняется проверка кода (запрос отправляется после ввода цифры в четвертом окошке) 

Апи подтверждения email ([post /auth/register/confirm-email)](https://212.233.78.3:8080/swagger/docs/index.html#/Auth/post_auth_register_confirm_email)
Тело запроса:
```
{
  "code": "1111", // четырехзначный код из письма (/dev/verification-code/get)
  "token": "string" //токен пользователя, который получен в теле ответа /auth/register (поле "token")
}
```
* Успешный ответ (`200`, пример):
```
{
  "access_token_life_time": 900000000000, 
  "message": "Successfuly confirmed email",
  "refresh_token_life_time": 2592000000000000,
  "status_code": 200,
  "token_details": {
    "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDgzNzIxMDQsInN1YiI6IjU2In0.P0ZM-j6LKvAQBs4HONwW6uQCGPK8Wl5Abd_357GXmwU",
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NiJ9.GgH0R2ysgIkxWz4gtLJoj1X8T0mTilmvf_Vp1rfwODU",
    "expires_at": 1710963204
  }
}
```
* Пример ответа, если пользователь неверно ввел код (401)
```
{"remaining_attempts":2, // количество оставшихся попыток
"lock_duration":0, // статус блокировки
"error":"Invalid confirmation code.", // сообщение
"status_code":401}
```
* Пример ответа, если пользователь заблокирован ( 401)
```
{"remaining_attempts":0, //  количество оставшихся попыток
"lock_duration":191359993737, // оставшееся время блокировки в наносекундах, блокировка на 5 минут
"error":"User is locked. Try again later.", // сообщение
"status_code":401}
```
- Успешный ответ приводит к выполнению сценария ~“Установить и подтвердить код подтверждения для входа в приложение”  #59 (в бэклоге)~ "Просмотр экрана аналитики". Авторизация не требуется, Access Token получен.
- Ответ с ошибкой приводит к отображению текста ошибки (pop-up):

Макета нет: 
`"error":"Invalid confirmation code."`
*Неправильный код подтверждения. Пожалуйста, введите корректный код*

`"error":"User is locked. Try again later." `
*Количество попыток ввода кода исчерпано. Пожалуйста, повторите позднее* и пользователь перенаправляется на стартовую страницу

`400        Bad Request - Invalid token or missing Content-Type header `      *Произошла ошибка при обработке Вашего запроса. Пожалуйста, проверьте введенные данные и повторите попытку. Если проблема сохраняется, обратитесь в [поддержку](ссылка на экран "Поддержка").*        
`401        Unauthorized - Invalid or expired token`       *Срок действия кода истек, повторите попытку.*        // ошибка приводит к сбросу кода, пользователь перенаправляется к предыдущему экрану (регистрация или авторизация)
`500        Internal Server Error - Failed to confirm email or register user`       *Внутренняя ошибка сервера - Не удалось подтвердить адрес электронной почты. Повторите попытку позднее. Если проблема сохраняется, обратитесь в [поддержку](ссылка на экран "Поддержка").*        // ошибка приводит к сбросу кода, пользователь перенаправляется к предыдущему экрану (регистрация или авторизация)

Диаграмма последовательности процесса регистрации
Изначально 3 попытки, если они закончились - то пользователь блокируется, если заблокирован - в ответе сервера выдается время оставшейся блокировки

![image](https://github.com/CashAdv/CashADV/assets/80758874/01bd8126-2fc2-424b-b4c4-f28852583199)

**Экран ввода пароля (макет):** [Enter verification email code](https://www.figma.com/file/jZ6rHddBpxOdgl1uPAvyWI/Cash-Advisor-App?type=design&node-id=2246-1581&mode=dev)

### Описание объектов
|  | **Атрибут** | **Тип данных** | **Обязательность** | **Валидация** | **Описание** |
| --- | --- | --- | --- | --- | --- |
| 1 | Код из письма | Число | да | Количество символов: 4 Регулярное выражение: ^[0-9]{4}$ Пример: 8878| Заполняется пользователем при подтверждении почты (UC-2) |

**Comment by avanisimov** [comment]
мне всё понятно, лайк

**Comment by katana-13** [comment]
Дубль #57
