### ISSUE TITLE
Авторизация в приложении

### ISSUE THREAD

**Issue by katana-13** [CashAdv/CashADV#60]
## Подзадачи
- [x] #79
- [x] #80
- [x] #81
- [x] #82

## UC-34 Авторизация  (после нее следует  #70)
**Предусловие:**
Пользователь зарегистрирован и не авторизован в приложении
**Триггер:**
 Пользователь нажал кнопку «Войти» на экране[ **New user**](https://www.figma.com/file/jZ6rHddBpxOdgl1uPAvyWI/Cash-Advisor-App?type=design&node-id=170-479&mode=design&t=Gt04foDgyf33cI0e-4) (ссылки на макеты экранов также в конце задачи), выполнен сценарий "Запуск приложения" UC-0 (#48)

**Критерии приемки:**
⚡ data и domain слой для логина, регистрации и кодов подтверждения для логина и регистрации, а также валидация для email, пароля и кодов подтверждения реализована в рамках #54 и #55

1. Система отображает пользователю экран [Login page](https://www.figma.com/file/jZ6rHddBpxOdgl1uPAvyWI/Cash-Advisor-App?type=design&node-id=2246-1446&mode=dev)
На странице Login page пользователь может 
*  Вернуться к странице [New user](https://www.figma.com/file/jZ6rHddBpxOdgl1uPAvyWI/Cash-Advisor-App?type=design&node-id=170-479&mode=design&t=ktiRxKqdzdVbGbwQ-4) (Нажать кнопку “Назад”)
* Перейти к восстановлению пароля (при нажатии на текстовую ссылку “Забыли пароль” осуществляется переход к сценарию UC-4: Восстановить пароль)
* Войти в приложение с помощью логина и пароля 
2. Пользователь может ввести email и пароль в поля формы авторизации  
3. Система проверяет корректность ввода пользователем значений 
![image](https://github.com/CashAdv/CashADV/assets/80758874/283c16bb-1496-4e65-81af-83b45826c248)
Если есть ошибки валидации:
https://www.figma.com/file/jZ6rHddBpxOdgl1uPAvyWI/Cash-Advisor-App?type=design&node-id=3134-2003&mode=design&t=I1BmaQgOCTAfEEIJ-4
В рамках mvp кастомизированное уведомление (Popups example animation) не реализуем
![image](https://github.com/CashAdv/CashADV/assets/80758874/62c09991-1c76-411a-b17e-8ed4c498af47)

### Описание объектов
**1. email**: *Строка*, *Обязательный*
**Количество символов**: 7-114
**Регулярное выражение**: ```^(?!.*[_.-]{2,})(?!.*[_.-]$)(?!^[-_.])[a-zA-Z0-9._-]{1,49}[a-zA-Z0-9]@(?!-)[a-zA-Z0-9-]{1,63}(\.[a-zA-Z]{2,})+$|^.{7,114}$```
Пример: test@mail.ru
*Заполняется пользователем при регистрации (UC-1)*

**2. пароль**: *Строка*, *Обязательный*
**Количество символов**: 8 - 30 
**Регулярное выражение**: ```^[a-zA-Z0-9_]{8,30}$``` 
Пример: Password123
*Заполняется пользователем при регистрации (UC-1)*

4. После ввода пользователем валидных  email и пароль, становится активна кнопка “Войти”.
После нажатия на кнопку система обращается к серверу ([/auth/login](https://212.233.78.3:8080/swagger/docs/index.html#/Auth/post_auth_login)) и проверяет наличие данных и соответствие email хэшированному паролю. 
* Если успешный ответ, то сервером инициируется отправка на указанный email кода подтверждения. Переход к сценарию "Подтверждение email" UC-2.1 (#70)
* Если ошибки - пользователю отображается текст ошибки (pop-up) 
  Возможные ошибки -[ в документации](https://212.233.78.3:8080/swagger/docs/index.html#/)
![image](https://github.com/CashAdv/CashADV/assets/80758874/3627d587-9d31-4122-8594-9d5704f413f2)

[Api  для получения четырехзначного кода для разработки (отправка кода на email)](https://212.233.78.3:8080/swagger/docs/index.html#/Dev/get_dev_confirmation_code_get)

**Экраны**: 
New User: https://www.figma.com/file/jZ6rHddBpxOdgl1uPAvyWI/Cash-Advisor-App?type=design&node-id=170-479&mode=design&t=Gt04foDgyf33cI0e-4
Login page: https://www.figma.com/file/jZ6rHddBpxOdgl1uPAvyWI/Cash-Advisor-App?type=design&node-id=2246-1446&mode=dev

**Comment by avanisimov** [comment]
я бы убрал из этой задачи упоминание о ВК или Google. Они всё равно сейчас не будут работать.
Лучше оставить только самый базовый сценарий и сделать его, а потом уже доработками добавить вк/емейл

Текст ошибок я предлагаю брать от бекенда, на клиенте ничего не хардкодить

**Comment by katana-13** [comment]
Убрала авторизацию через соцсети
Убрала описание ошибок
