### ISSUE TITLE
Добавить иконку приложения в проект

### ISSUE THREAD

**Issue by vikseal** [CashAdv/CashADV#7]
https://www.figma.com/file/jZ6rHddBpxOdgl1uPAvyWI/Cash-Advisor-App?type=design&node-id=1049-2098&mode=design&t=0sbH1rzDd4pPPuZo-4

**Comment by vikseal** [comment]
Предлагаю такой флоу, по задачам без PR: если считаем, что задача выполнена, пишем мне или переносим сами в реди и тегаем в комментах к ишшузу Лешу, или я это делаю, если переношу я.
Переоткрою, тэгни Лешу, пожалуйста, перед закрытием

**Comment by alexxk2** [comment]
Привет, тут  есть уже закрытый PR, поэтому я его перенес в done
